### ISSUE TITLE
E-Mail-Template

### ISSUE THREAD

**Issue by katgirl** [terminal42/contao-notification_center#13]
You can't select an e-mail-tempalte that is in a project-template-directory.

![image](https://f.cloud.github.com/assets/1223243/1642124/8fa426dc-5872-11e3-990d-c97f57e1600b.png)

**Comment by Toflar** [comment]
Isotope does it per store config...we don't have any config. Should it just display all templates? I tend to dislike that approach and just close the issue as known limitation.

**Comment by aschempp** [comment]
With "similar to Isotope" I didn't mean the store config, I meant just showing everything. If it works depends on the active theme. The same has been implemented in other Contao core modules as far as I know.

**Comment by Toflar** [comment]
> The same has been implemented in other Contao core modules as far as I know.

For example?

**Comment by Toflar** [comment]
Well I found that the limitation per theme was removed in Contao 3.0 - very long ago. You can find the discussion and related commits here: https://github.com/contao/core/issues/5095

However, this lead to problems when sending newsletters which is why `mail_` templates are explicitly exempt from this new behaviour. Discussion and related commits: https://github.com/contao/core/issues/5379

So I am closing this as we will not introduce a behaviour that is different from the one in Contao.
