### ISSUE TITLE
file upload attachment fails when filename contains ,

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-notification_center#138]
Might probably be related to https://github.com/terminal42/contao-notification_center/issues/24
When a user uploads a file wich is going to be attached to a notification message and this file has a ```,``` in its name it wont be attached.

![image](https://user-images.githubusercontent.com/4138336/33877419-97148056-df28-11e7-8f52-011de787c0ef.png)

addendum:
if you pick such a file from the internal file-picker and not via the attachment-token it's properly attached.

**Comment by rabauss** [comment]
this is caused by https://github.com/terminal42/contao-notification_center/issues/97

but at the moment I'm not sure about a possible solution.
we will temporarily solve it by overwriting the ``FormFileUpload`` of core and will set a valid fileName without comma.

unfortunately the method ``sanitizeFileName`` in ``Contao\StringUtil`` cannot be extended.
