### ISSUE TITLE
Tracking ID in Notification Message

### ISSUE THREAD

**Issue by floespen** [terminal42/contao-notification_center#202]
Is there an existing way to add some kind of tracking ID to a notification message. The tracking id should be unique and in best case incremental (or just the ID of the notification itself).

**Comment by aschempp** [comment]
Can you explain why this would make sense?

**Comment by floespen** [comment]
We want a reference to the notification so we can refer to it later on. This would be useful for customer notifications.

**Comment by Toflar** [comment]
You mean something like `[{{uniqueid}}] Foobar` as the subject?

**Comment by floespen** [comment]
Yes, something like that would be great.

**Comment by asaage** [comment]
side note:
if you use the contao-feature "store form data" in conjunction with a notification_center-message it would be really nice if one could utilise something like ```##form_id##``` to create a link with parameter to the detail-view of a listing-module for example.
I figured that this is not possible probably due to the order of operations (notification first - then DB-insert?)
Such a reference would me much more useful than an arbitary ```uniqueid``` which is most likely not related to anythig stored in the database.

```##form_id##``` in this cas should of course not return the id of the form but the autoincremented id of the form-submission.

**Comment by floespen** [comment]
What about this:
Detect in notification-center if leads is active, 

    $GLOBALS['TL_HOOKS']['processFormData'][]       = array('NotificationCenter\tl_form', 'sendFormNotification');

change this to use the 

    $GLOBALS['TL_HOOKS']['storeLeadsData']

instead?

Could that work? Would that have changes to be merged?

**Comment by Toflar** [comment]
I don't see any value in this, so I'm closing it. However, in [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277) there will be a whole new concept and tons of extension points to implement this in a clean and simple way. So it might very well be something that could be implemented by a third party extension.
