### ISSUE TITLE
Invalid characters lead to issues in queue

### ISSUE THREAD

**Issue by koertho** [terminal42/contao-notification_center#248]
**Context:**
Contao 4.9.22
PHP 7.4.25

**Description:**
When a message added to the queue with invalid characters for json_encode(), no error is thrown or shown, but the token list is stored empty (this is for example the case with binary file uuids). When the messages are send, the queue says "Error sending the message. Check the system log for more details." (as also no recipient token is available so there are no recipients), but there is no error in the system log or log files.

**Possible solutions:**
- Trigger an error if `json_encode()` returns false here https://github.com/terminal42/contao-notification_center/blob/18f4145f4529d169e447ee0a806fab0a22336e44/library/NotificationCenter/Model/QueuedMessage.php#L29
- Log some kind of error here: https://github.com/terminal42/contao-notification_center/blob/18f4145f4529d169e447ee0a806fab0a22336e44/library/NotificationCenter/Gateway/Email.php#L162

I would offer to create a PR for this issue, but I didn't like to start before you have a favored solution (or another/ better idea).

**Comment by fritzmg** [comment]
I would at least throw a `\RuntimeException` in `QueuedMessage::getToken`.

**Comment by koertho** [comment]
Proposel: Add an token filter here: https://github.com/terminal42/contao-notification_center/blob/18f4145f4529d169e447ee0a806fab0a22336e44/library/NotificationCenter/Queue/QueueManager.php#L54

```php
if (false === json_encode($tokens) {

  $cleanedTokens = [];
  
  foreach ($tokens as $k => $v) {
      if (\json_encode($v) !== false) {
          $cleanedTokens[$k] = $v;
      }
  }
  $tokens = $cleanedTokens;
}
 $objQueuedMessage->setTokens($tokens);
```

This would fix any invalid character related issues.

**Comment by koertho** [comment]
Hi, should I do a PR with the former proposel? Maybe with an additional checkbox in the message to opt-in ("Filter invalid tokens").

**Comment by Toflar** [comment]
This gateway seems to be used extremely rarely. I've used it once in ten years for a project which is when I've contributed it to the core. Ever since, nobody else has been contributing to it. Thus, in [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277) support for the queue will be dropped for sure.
I need to do some cleanup here.

**Comment by koertho** [comment]
What? We only use the queue gateway. I can't image others don't?

**Comment by Defcon0** [comment]
😱😱😱

The queue is a very nice way to see which email has been send at which time and using what tokens. @Toflar Inferring from oneself to others is often not the right path.

**Comment by Toflar** [comment]
Fact is: Nobody has been maintaining it for years. All we had are issues that have been ignored by everybody. Including me - simply because I don't care about that gateway as non of my customers uses it. How is that helpful to anyone? 
It doesn't matter whether I think people need it or not. Notification Center 2.0 is a complete rewrite. I have already spent 100+ hours (!) on it. Now I'll give you the number of reasons for me to work on that queue gateway on top in my spare time: 0.

The only reason for me to do that would be if it were a paid extension. Then I'd have a reason to work on it, to care about it and to maintain it. And you guys have a solution to go to and a place where you can actually get support rather than having an issue that floats around on GitHub being ignored by everyone 😊 

I might actually consider that if there's enough interest (feel free to react 👍 on this comment, then I know).

But in any case: Don't worry, the world is not going to end because of this and there will be a solution. There always is 😊
