### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by rorych** [terminal42/contao-notification_center#253]
Hi there

I am setting up a reset password function with nc, but i can't get it to work.
I can fill the form and send it. It gets added to the queue. But when the message should be sent from the queue, it fails with a error message (in var/logs):

> [2022-01-28 16:48:35] contao.INFO: Tried to parse unknown simple token "link". [] []  
> [2022-01-28 16:48:35] contao.INFO: Tried to parse unknown simple token "recipient_email". [] []

But in your code, you add these fields to be valid:
https://github.com/terminal42/contao-notification_center/blob/068f8680dd0e0d2f9f1d9b8e69a86cd726348166/config/config.php#L163
https://github.com/terminal42/contao-notification_center/blob/068f8680dd0e0d2f9f1d9b8e69a86cd726348166/config/config.php#L166

I have the ##recipient_email## in the "Recipients" Field and the ##link## in the email_text and email_html.

So i don't understand why contao would "block" the usage of these tokens.
Have you ever had this problem or do you have an idea, why this happens?

_PHP 7.4
Contao 4.9.24
Notification Center 1.6.5_

**Comment by aschempp** [comment]
does it work if you don't use the queue?

**Comment by Toflar** [comment]
This gateway seems to be used extremely rarely. I've used it once in ten years for a project which is when I've contributed it to the core. Ever since, nobody else has been contributing to it. Thus, in [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277) support for the queue will be dropped for sure.
I need to do some cleanup here.
