### ISSUE TITLE
Simple-Token autocomplete not working in TinyMCE (HTML)

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-notification_center#270]
- Notification Center 1.6.13
- Contao 4.13.6
- PHP 8.1

If I type `##` in the RAW text-window, then autocomplete comes up automatically for me.
If I enable text and HTML and try to do the same in TinyMCE, then autocomplete does not show up.

Currently, I could only reproduce the problem under Contao 4.13 because under Contao 4.9 it still works as expected.

![screen-20220720_4R2U26GF](https://user-images.githubusercontent.com/23719181/180005382-d8b87abc-77a3-447b-9fb3-4c2b7acc3b62.jpg)

**Comment by cliffparnitzky** [comment]
Can confirm. The developer console throws an error.

**Comment by contaoacademy** [comment]
Maybe the same issue as #262

**Comment by philvdb** [comment]
@contaoacademy possibly, but the behavior is slightly different. TinyMCE does not load for me at all when I use Contao 4.13.

**Comment by philvdb** [comment]
Now that my tinyMCE is showing again I was able to look into the autosuggester problem. I'm not familiar with tinyMCE at all but the problem seems to be in `assets/autosuggester.js:164`:

```JavaScript

        // Add the events to tinyMCE
        if (this.tinyMCE) {

            if (window.tinyMCE.majorVersion == '4') {
                this.tinyMCE.on('keyUp', function(event) {
                   this.eventKeyUp.call(this, event);
                }.bind(this));
```

`window.tinyMCE` is not defined, `this.tinyMCE` is. However, `this.tinyMCE` does not have a property called `majorVersion` or `version` at all at least in my installation. This means that the check for version 4 fails and the nonexistent property `onKeyUp` causes the error in our developer consoles.

Knowing virtually nothing about tinyMCE I don't know if this is the proper solution. However at least in my installation, instead of looking for the version number checking for the existence of the `on` function leads to the autosuggester working again:

```JavaScript
        // Add the events to tinyMCE
        if (this.tinyMCE) {

            if (typeof this.tinyMCE.on === 'function') {
                this.tinyMCE.on('keyUp', function(event) {
                   this.eventKeyUp.call(this, event);
                }.bind(this));
```

Let me know if this is the right approach I could try creating a pull request .. would have to figure out how to minify the Javascript properly though :clown_face: . If switching out the line and minifying the JS is something that comes easy in your development workflow I will be happy if anyone else wants to do it.

**Comment by philvdb** [comment]
@contaoacademy , @cliffparnitzky feel free to try out https://github.com/philvdb/contao-notification_center to see whether it solves the problem for you as well and report back here.

**Comment by contaoacademy** [comment]
@philvdb Looks great! Works for me. Thank you.
