### ISSUE TITLE
Difference of PHP Version Requirements in Composer vs. README

### ISSUE THREAD

**Issue by Shadow-Devil** [terminal42/contao-notification_center#303]
In the README it is stated, that version 1.7.* is only supported for PHP ^8.1
https://github.com/terminal42/contao-notification_center/blob/5e6765d2dd3221cf16d831851c9779514b67783c/README.md?plain=1#L10-L16

But this is not reflected in the `composer.json` where the version constraint is `^7.0 || ^8.0`
https://github.com/terminal42/contao-notification_center/blob/5e6765d2dd3221cf16d831851c9779514b67783c/composer.json#L32-L33

Solution: Update the `composer.json`with a version constraint of `^8.1`

**Comment by aschempp** [comment]
I think the point here is that `codefog/contao-haste` only supports PHP 8.1 in version 5. So the constraints are actually true, even if the code base of `terminal42/notification_center` still supports PHP 7.

Since we're about to release Notification Center 2.0, I don't think its worth investing time here. Thanks for reporting anyway though!
