### ISSUE TITLE
Notifications not sent

### ISSUE THREAD

**Issue by thomas-mgh** [terminal42/contao-notification_center#329]
Notifications aren't sended any more after update from Contao 4.13 to Contao 5.3.7 and Notification Center 2.0.4.

**Comment by zoglo** [comment]
@thomas-mgh, it's unclear what you mean. Please add more details:
- What type of notification doesn't work?
- Do you use other plugins / did you code your own gateway?

____

#### Are you able to fill out normal contao forms and receive e-mails?

> Unrelated issue - set up your e-mail settings
    https://docs.contao.org/manual/en/system/settings/#mailer-dsn
    https://docs.contao.org/manual/en/system/settings/#e-mail-sending-configuration

#### Did you read the [UPGRADE.md](https://github.com/terminal42/contao-notification_center/blob/main/UPGRADE.md)?

- The built-in queue gateway has been removed
- The Notification Center integration for the Contao core "Registration" front end module has been changed. If you want to use the Notification Center to send registration e-mails, update to the new "Registration (Notification Center)" module. Also see docs.
- `contao/newsletter-bundle` integration: If you did use the "Activate (Notification Center)" front end module, you will have to adjust your workflow. This module has been removed. However, the "Subscribe (Notification Center)" now has a second forward page setting. You can use this one in order to have a separate confirmation page.

#### Did you read the documentation?

- https://extensions.terminal42.ch/docs/notification-center/en/users/

**Comment by fritzmg** [comment]
@thomas-mgh if you need general help regarding the Notification Center you can also post on the Contao Community Forum or the Community Slack.

**Comment by thomas-mgh** [comment]
I use Notification Center only to confirm the sender the data which are sent with the form. It is not used for registration of a newsletter or something else. There are no other plugins installed. MAILER_DSN is configured correctly. In addition I configured three different Mailer-Transports in config.yml as described in the Contao Manual. The form is sent, but the notification not. I posted my problem in Contao Forum, but unfortunatly couldn't solve it until now. Thank you for your help.

**Comment by mlwebworker** [comment]
Bitte den Link zum Forumsbeitrag hinzufügen. 
Ich denke aber auch, das Slack oder das Forum für diese Art von Fragen der bessere Ort sind.

**Comment by thomas-mgh** [comment]
Danke für den Hinweis. Die Version 2.0.7 werde ich gleich testen.

**Comment by Toflar** [comment]
Es gibt keinen Grund für eine 2.0.7, da kein Bug reported wurde. Ich schliesse dieses Ticket, da dies ein Bugtracker und kein Support-Forum ist. Bitte nutzt die entsprechenden Kanäle. Sollte sich dabei herausstellen, dass es sich tatsächlich um einen Fehler handelt, dann gerne ein Ticket mit Fehlerbeschreibung und Anleitung, wie das Problem Schritt für Schritt nachvollzogen werden kann.

**Comment by fritzmg** [comment]
@thomas-mgh if you have a "friendly admin email address" set in your system config or website root (i.e. `Firstname Lastname [email@example.com]` or `Firstname Lastname <email@example.com>`) this might be a reason why notifications are not sent: #336 (there will also be no system log entry for the error currently: #335).
