### ISSUE TITLE
Argument #2 ($metadata) must be of type Contao\CoreBundle\Filesystem\ExtraMetadata, array given

### ISSUE THREAD

**Issue by franklytom** [terminal42/contao-notification_center#370]
Folgenden Fehler erhalte ich:
```
Contao\CoreBundle\Filesystem\VirtualFilesystem::setExtraMetadata():
Argument #2 ($metadata) must be of type Contao\CoreBundle\Filesystem\ExtraMetadata, array given, called in …/vendor/terminal42/notification_center/src/BulkyItem/BulkyItemStorage.php on line 35
```

Der Aufruf kommt aus folgendem Abschnitt:
```
$fileItem = FileItem::fromPath($filePath, $fileName, $mimeType, $fileSize);  
$voucher = $this->notificationCenter->getBulkyItemStorage()->store($fileItem);
```

store() wiederum enthält in der entscheidenden Passage:
```
$meta = [  
   'item' => $item->getMeta(),  
   'class' => $item::class,  
];         
$this->filesystem->setExtraMetadata($voucher, ['storage_meta' => $meta]);
```

setExtraMetadata erwartet jedoch tatsächlich als zweiten Parameter keinen Array:
```
public function setExtraMetadata(Uuid|string $location, ExtraMetadata $metadata): void
```

Ich bin gerade ein bisschen ratlos wo ich ansetzen könnte. Aktuell bin ich dabei meine Erweiterung von Contao 4.13 auf 5.4 umzustellen und bin bei diesem Upgrade auf das Verhalten gestoßen.

Versionen: PHP 8.3
Contao 5.4.4
Notification Center Pro: 1.0.3

**Comment by fritzmg** [comment]
> Ich bin gerade ein bisschen ratlos wo ich ansetzen könnte.

This is a breaking change in the recent Contao version (note: the VFS is marked as experimental thus breaking changes are ok here). NC hasn't been updated yet to adjust its own implementation accordingly.

**Comment by franklytom** [comment]
I have the same problem at Contao 5.3.
Which is the lastet known version? 
Or do you already know when you will adjust the NC?

**Comment by christianbarkowsky** [comment]
I can also confirm this under Contao 5.3

**Comment by Toflar** [comment]
I was on vacation. I will tackle this issue as soon as there is a possibility for me to tackle it. Currently, there is no Contao 4.13 release with the adjusted VFS interface so there's no way for me to be compatible with both, 4.13 and the latest changes in 5.3 and 5.4. This has to be fixed in 4.13 first (and a relase has to be published). Until then, I'm afraid but you'll have to downgrade to 5.4.3 or 5.3.15.

**Comment by Toflar** [comment]
I've found a solution anyway and released 2.1.1. I have adjusted the requirements in the `composer.json` so that only users of the latest 5.3 and 5.4 (which are affected) will get the bugfix release. The 4.13 requirement is adjusted to a release that is not published yet but will include the backport of the adjustments. So 2.1.1 is not available for 4.13 users but will be as soon as there is 4.13.50 which will contain the backport and then everybody should be good again.

**Comment by franklytom** [comment]
@Toflar is the problem also fixed for the pro version? As fat as I can see for the Pro-Version NC is fixed to         "terminal42/notification_center": "^2.0" so would not get the 2.1.1. Is that right?

**Comment by Toflar** [comment]
`^2.0` means anything `>= 2.0 && < 3.0`. But you can just test it and then you know? 😄

**Comment by franklytom** [comment]
-_- I'm running terminal42/contao-notification-center-pro in Version 1.0.3. and Contao 5.4.4. and the ExtraMetadata-error is back again. That's why I'm a bit confused.

**Comment by franklytom** [comment]
Thanks Toflar!
