### ISSUE TITLE
member_gender output

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-notification_center#49]
Added the following line to the langconfig.php:

``` php
$GLOBALS['TL_LANG']['MSC']['male'] = 'Mister';
```

The output in the notifications:
Member registration = member_gender: **Mister**
Member lost password = member_gender: **male**

**Comment by Toflar** [comment]
That's a really stupid problem we should fix somehow. Any ideas @aschempp @qzminski

**Comment by qzminski** [comment]
How is that possible?

**Comment by Toflar** [comment]
Because of

https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/ContaoHelper.php#L78 (`\Haste\Util\Format::dcaValue('tl_member', $strFieldName, $strFieldValue);`)

and

https://github.com/terminal42/contao-notification_center/blob/master/modules/ModulePasswordNotificationCenter.php#L59-L61

**Comment by qzminski** [comment]
And why can't we use Haste there?

**Comment by Toflar** [comment]
Because it's pretty stupid for some values. E.g.

```
{if member_gender=="male"}
[...]
```

That totally makes sense for gender-specific salutations. However, in the registration e-mail you can't do that because on a multilingual site you would need to do something like

```
{if member_gender=="Herr" || member_gender=="Mr"}
[...]
```

So the best thing would be to actually use

```
##member_raw_*##
```

and

```
##member_*##
```

But we can't just switch the behavior now as it would cause all existing notifications to fail.

**Comment by aschempp** [comment]
I suggest to fix this in v2.0

**Comment by qzminski** [comment]
If you plan it for next major version, then I think you can also think about having even more display options. Something similar to what Twig does:

```
{{ member_title }} // Herr
{{ member_title.raw }} // male
{{ member_name|strtoupper }} // JOHN
{{ member_dateCreated.raw|date('d-m-Y') }} // 06-02-2015
```

Maybe there already exists a parser we could implement?

**Comment by aschempp** [comment]
You're probably looking for the Symfony Expression Language ;-)

**Comment by Toflar** [comment]
Nope, he's not. He's right about Twig :) The EL is the wrong tool for this because it does not output data :)

**Comment by qzminski** [comment]
The EL could at some point be implement as well and replace the current {if} tags.

**Comment by Toflar** [comment]
> I suggest to fix this in v2.0

:+1:

**Comment by aschempp** [comment]
We could fix this in a current version by providing the values in member registration module. There's a Haste insert tag `{{dca_value:: … }}` for exactly this purpose. However, it would be a sort-of BC change…

**Comment by Toflar** [comment]
In NC 2 I have unified the `member_*` tokens in all notification types to represent the formatted value. The raw values are available with a new `member_raw_*` token which is also available in all other notification types.
